development: 
  access_key_id: AKIAII6QRJITJ7RU3STQ
  secret_access_key: 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
  
staging: 
  access_key_id: AKIAII6QRJITJ7RU3STQ
  secret_access_key: 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
  
production: 
  access_key_id: AKIAII6QRJITJ7RU3STQ
  secret_access_key: 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
